import "./globals.css";
import { Maven_Pro } from "next/font/google";
import Header from "@/components/layout/Header";

const font = Maven_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "E-COMMERCE HACKATHON-1",
  description: "Generated by Mirza Ziyad Ahmed Baig for practise of hackathon",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <main className="wrapper">
        {children}
        </main>
      </body>
    </html>
  );
}
